Repository 2023-Summer-Bootcamp-Team-B/RelaySketch, pull requests merged in 2023-08, with the labels that each got.

#99 Fix : 게임 시작 후 플레이어가 들어와지는 오류 해결
  backend/Pipfile
  backend/myapp/consumers.py
Labels: 오류수정

#92 [Feat] 카카오톡 공유 API를 이용한 게임 결과 공유하기 기능 구현 완료
  docker-compose.yml
  frontend/.env.example
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/src/assets/images/kakao_share_button.png
  frontend/src/components/ResultsList/Result.tsx
  frontend/src/components/ResultsList/ResultsList.tsx
  frontend/src/components/UI/KakaoShareButton.tsx
  frontend/src/stores/WebsocketStore.ts
  frontend/src/vite-env.d.ts
  frontend/vite.config.ts
Labels: 기능구현

#100 Fe/#79 반응형 디자인
  frontend/src/assets/images/border1.png
  frontend/src/assets/images/new_button.png
  frontend/src/assets/images/인원수테두리1.svg
  frontend/src/assets/images/입력창테두리1.svg
  frontend/src/components/Background.tsx
  frontend/src/components/PlayerList/PlayerList.tsx
  frontend/src/components/PlayerList/PlayersSection.tsx
  frontend/src/components/ResultsList/Result.tsx
  frontend/src/components/ResultsList/ResultsList.tsx
  frontend/src/components/ResultsList/ResultsSection.tsx
  frontend/src/components/UI/AnimatedFooter.tsx
  frontend/src/pages/GuessImagePage.tsx
  frontend/src/pages/InputTitlePage.tsx
  frontend/src/pages/LoadingPage.tsx
  frontend/src/pages/MainPage.tsx
  frontend/src/pages/PlayerRoomPage.tsx
Labels: 스타일

#101 FIX : conflict 및 웹페이지 이동관련 예외처리 완료.
  frontend/src/components/Background.tsx
  frontend/src/components/ResultsList/Result.tsx
  frontend/src/pages/GuessImagePage.tsx
  frontend/src/pages/InputTitlePage.tsx
  frontend/src/pages/LoadingPage.tsx
  frontend/src/pages/PlayerRoomPage.tsx
  frontend/src/stores/WebsocketStore.ts
Labels: 오류수정

#103 FIX: 스케치북 이미지 위치 조정 및 불필요한 콘솔로그 제거, 텍스트 변경
  frontend/src/components/Background.tsx
  frontend/src/components/ResultsList/Result.tsx
  frontend/src/pages/GuessImagePage.tsx
  frontend/src/pages/PlayerRoomPage.tsx
Labels: 오류수정

#104 README.md
  README.md
Labels: 문서

#105 Update README.md
  README.md
Labels: 문서

#107 README.md
  README.md
Labels: 문서

#109 Chore: 브라우저 탭 타이틀 및 아이콘 변경
  frontend/index.html
Labels: 기타/세팅

#110 README.md
  README.md
Labels: 문서
