Repository 2023-Summer-Bootcamp-Team-B/RelaySketch, pull requests merged in 2023-07, with the labels that each got.

#4 Chore : 프론트엔드 기초 세팅
  frontend/.eslintrc.cjs
  frontend/.gitignore
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/public/vite.svg
  frontend/src/App.css
  frontend/src/App.tsx
  frontend/src/assets/react.svg
  frontend/src/index.css
  frontend/src/main.tsx
  frontend/src/pages/MainPage.tsx
  frontend/src/vite-env.d.ts
  frontend/tsconfig.json
  frontend/tsconfig.node.json
  frontend/vite.config.ts
Labels: 기타/세팅

#6 Be/#5 백엔드 기초 세팅
  .env.example
  .gitignore
  .vscode/settings.json
  Pipfile
  backend/asgi.py
  backend/config/__init__.py
  backend/config/asgi.py
  backend/config/settings.py
  backend/config/urls.py
  backend/config/wsgi.py
  backend/gunicorn.conf.py
  backend/main.py
  backend/manage.py
  backend/myapp/__init__.py
  backend/myapp/admin.py
  backend/myapp/apps.py
  backend/myapp/consumers.py
  backend/myapp/migrations/__init__.py
  backend/myapp/models.py
  backend/myapp/routing.py
  backend/myapp/tests.py
  backend/myapp/views.py
  backend/routing.py
Labels: 기타/세팅

#11 Chore: eslint 세팅
  frontend/.eslintrc.cjs
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/pages/LoadingPage.tsx
  frontend/src/pages/ResultsPage.tsx
Labels: 기타/세팅

#13 Be/#12 도커 세팅
  .dockerignore
  .env.example
  .gitignore
  Pipfile
  backend/.dockerignore
  backend/Dockerfile
  backend/Pipfile
  backend/config/settings.py
  backend/config/urls.py
  backend/myapp/views.py
  docker-compose.yml
  frontend/.gitignore
  frontend/Dockerfile
  frontend/package-lock.json
  frontend/src/App.tsx
  frontend/vite.config.ts
  nginx/dockerfile
  nginx/nginx.conf
Labels: 기타/세팅

#15 Be/#14 모델 작성
  backend/myapp/models.py
  nginx/nginx.conf
Labels: 기능구현

#17 Be/#16 Pycharm 문법 오류 수정
  backend/Pipfile
  backend/myapp/admin.py
  backend/myapp/consumers.py
  backend/myapp/models.py
  backend/myapp/tests.py
  backend/myapp/views.py
  nginx/nginx.conf
Labels: 오류수정

#20 fix : routing 수정
  .github/auto_assign.yml
  backend/config/urls.py
  backend/myapp/consumers.py
  backend/myapp/models.py
  backend/myapp/routing.py
  backend/routing.py
Labels: 오류수정

#22 Chore : 시간설정 및 model 수정
  backend/config/settings.py
  backend/myapp/models.py
Labels: 기타/세팅

#26 Feat : 방 만들기 api 기능 구현
  backend/myapp/routing.py
  backend/myapp/views.py
Labels: 기능구현

#31 [Fix] websocket error해결, cors, nginx 설정
  backend/Dockerfile
  backend/Pipfile
  backend/asgi.py
  backend/config/asgi.py
  backend/config/settings.py
  backend/myapp/apps.py
  backend/myapp/models.py
  backend/myapp/views.py
  backend/routing.py
  docker-compose.yml
  nginx/nginx.conf
Labels: 오류수정

#33 [FIX] 방장 subroom 삭제시 다른 서브룸에 방장 안넘어가는 문제 수정
  backend/myapp/models.py
Labels: 오류수정

#35 Feat : 웹소켓 연결 및 최대인원 제한
  backend/myapp/consumers.py
Labels: 기능구현

#36 [FEAT] 게임시작 API 구현
  backend/myapp/consumers.py
Labels: 기능구현

#42 Feat: 클라이언트에서 연결 핑 보내고 퐁 받기 및 서버에서 연결 핑 보내고 퐁 받기
  backend/myapp/consumers.py
Labels: 기능구현

#51 [Design] 결과 페이지 퍼블리싱 수정
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/assets/images/long_border.png
  frontend/src/components/PlayerList/Player.tsx
  frontend/src/components/PlayerList/PlayersSection.tsx
  frontend/src/components/ResultsList/Result.tsx
  frontend/src/components/ResultsList/ResultsList.tsx
  frontend/src/components/ResultsList/ResultsSection.tsx
  frontend/tailwind.config.js
Labels: 퍼블리싱

#54 Fe/#52 폰트 변경 및 결과 페이지 수정
  frontend/src/assets/fonts/BMJUA.ttf
  frontend/src/assets/fonts/HS유지체.ttf
  frontend/src/components/Background.tsx
  frontend/src/components/PlayerList/PlayersSection.tsx
  frontend/src/components/ResultsList/ResultsSection.tsx
  frontend/src/components/UI/AnimatedFooter.tsx
  frontend/src/index.css
  frontend/src/pages/LoadingPage.tsx
  frontend/src/pages/MainPage.tsx
  frontend/src/pages/PlayerRoomPage.tsx
  frontend/src/pages/ResultsPage.tsx
  frontend/tailwind.config.js
Labels: 퍼블리싱

#48 Be/#37 RabbitMQ. Celery세팅 및 text to image, papago 번역 API 연동
  .env.example
  backend/Dockerfile
  backend/Pipfile
  backend/config/__init__.py
  backend/config/celery.py
  backend/config/settings.py
  backend/myapp/consumers.py
  backend/myapp/models.py
  backend/myapp/tasks.py
  backend/myapp/views.py
  docker-compose.yml
Labels: 기능구현, 기타/세팅

#53 [FEAT] 주제 입력, 주제 편집, 라운드 이동 API, subroom Model 수정
  backend/myapp/consumers.py
  backend/myapp/models.py
Labels: 오류수정, 기능구현

#56 Fe/#55 Mobx, Axios 세팅, WS연결 테스트
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/pages/MainPage.tsx
  frontend/src/pages/PlayerRoomPage.tsx
  frontend/src/stores/WebsocketStore.ts
  frontend/tsconfig.json
  frontend/vite.config.ts
Labels: 기능구현, 기타/세팅

#61 Be/#60
  backend/myapp/consumers.py
Labels: 오류수정

#63 BE/#62 [Fix] 웹소켓 연결 끊김, url 전송오류
  backend/myapp/consumers.py
  backend/myapp/models.py
Labels: 오류수정

#40 chore : 장고에 그라파나와 프로메테우스 연동
  .gitignore
  backend/Pipfile
  backend/config/settings.py
  backend/config/urls.py
  docker-compose.yml
  grafana/grafana.ini
  prometheus/config/prometheus.yml
  prometheus/config/rule.yml
Labels: 기타/세팅, HELP!

#66 Feat: 결과보기
  backend/myapp/consumers.py
Labels: 기능구현

#67 Be/#64 [Fix] 다음 라운드 URL 전송, topic 생성 오류
  backend/myapp/consumers.py
  backend/myapp/models.py
Labels: 오류수정

#69 Feat: inputTitle 1 라운드 1번만 적용, 결과 전송에 player name 추가
  backend/myapp/consumers.py
  backend/myapp/models.py
Labels: 기능구현

#71 Be/#70 CI 적용
  .github/workflows/CI.yml
  backend/config/settings.py
  backend/myapp/models.py
  backend/myapp/test/__init__.py
  backend/myapp/test/test_models.py
  backend/myapp/test/test_views.py
  frontend/src/main.tsx
  frontend/src/pages/PlayerRoomPage.tsx
Labels: 기능구현

#78 Fe/#58 주제 입력 페이지 기능구현 및 API 연동
  frontend/src/App.tsx
  frontend/src/assets/images/버튼테두리1.svg
  frontend/src/components/Background.tsx
  frontend/src/pages/GuessImagePage.tsx
  frontend/src/pages/InputSubjectPage.tsx
  frontend/src/pages/InputTitlePage.tsx
  frontend/src/pages/PlayerRoomPage.tsx
  frontend/src/stores/WebsocketStore.ts
Labels: 기능구현

#77 chore : K6 세팅
  .dockerignore
  .gitignore
  docker-compose.yml
  k6dashboard/performance-test-dasboard.json
  k6dashboard/xk6-output-influxdb-dashboard.json
  k6http.js
  k6ws.js
Labels: 기타/세팅

#80 [Feat] 메인페이지 및 플레이어 룸 페이지 기능 구현 완료
  frontend/src/assets/images/crown.png
  frontend/src/pages/MainPage.tsx
  frontend/src/pages/PlayerRoomPage.tsx
  frontend/src/stores/WebsocketStore.ts
  frontend/tailwind.config.js
Labels: 기능구현

#81 [Feat] 라운드 변경API, 결과 보기API 연동 및 관련 기능 구현 완료
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Background.tsx
  frontend/src/components/Header/Header.tsx
  frontend/src/components/PlayerList/Player.tsx
  frontend/src/components/PlayerList/PlayerList.tsx
  frontend/src/components/PlayerList/PlayersSection.tsx
  frontend/src/components/ResultsList/Result.tsx
  frontend/src/components/ResultsList/ResultsList.tsx
  frontend/src/components/ResultsList/ResultsSection.tsx
  frontend/src/components/UI/Button.tsx
  frontend/src/pages/GuessImagePage.tsx
  frontend/src/pages/InputTitlePage.tsx
  frontend/src/pages/LoadingPage.tsx
  frontend/src/pages/MainPage.tsx
  frontend/src/pages/PlayerRoomPage.tsx
  frontend/src/pages/ResultsPage.tsx
  frontend/src/stores/WebsocketStore.ts
  frontend/tailwind.config.js
Labels: 기능구현

#82 HOTFIX : 플레이어 룸 페이지 링크 복사관련 오류 해결
  frontend/src/pages/PlayerRoomPage.tsx
Labels: 오류수정

#86 도커 파일 분리
  .github/workflows/CD.yml
  backend/config/settings.py
  docker-compose.monitor.yml
  docker-compose.prod.yml
  docker-compose.yml
  frontend/Dockerfile.prod
  frontend/package-lock.json
  frontend/package.json
  frontend/src/pages/MainPage.tsx
  frontend/src/pages/PlayerRoomPage.tsx
  logging/elasticsearch/.dockerignore
  logging/elasticsearch/Dockerfile
  logging/elasticsearch/config/elasticsearch.yml
  logging/filebeat/.dockerignore
  logging/filebeat/Dockerfile
  logging/filebeat/config/filebeat.yml
  logging/kibana/.dockerignore
  logging/kibana/Dockerfile
  logging/kibana/config/kibana.yml
  logging/logstash/.dockerignore
  logging/logstash/Dockerfile
  logging/logstash/config/logstash.yml
  logging/logstash/pipeline/logstash.conf
  nginx/nginx.conf
Labels: 기타/세팅

#88 Be/#87 API 문서화, node-exporter, cadvisor,alert manager 연동 완료
  .gitignore
  backend/Pipfile
  backend/config/settings.py
  backend/config/urls.py
  docker-compose.monitor.yml
  prometheus/config/alert.yml
  prometheus/config/prometheus.yml
Labels: 기타/세팅

#91 BE/#90 Fix: 혼자 이름 변경 후 오류 해결
  backend/myapp/consumers.py
  backend/myapp/models.py
Labels: 오류수정
